const AUTHENTICATED = 'AUTHENTICATED';
const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED';
const GET_COMPANY_LIST = 'GET_COMPANY_LIST';
const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST';
const GET_COMPETITION_LIST = 'GET_COMPETITION_LIST';
const GET_WOOCOMMERCE_LIST = 'GET_WOOCOMMERCE_LIST';
const GET_WOOCOMMERCE_ORDER_LIST = 'GET_WOOCOMMERCE_ORDER_LIST';

export {
    AUTHENTICATED,
    NOT_AUTHENTICATED,
    GET_PRODUCT_LIST,
    GET_COMPANY_LIST,
    GET_COMPETITION_LIST,
    GET_WOOCOMMERCE_LIST,
    GET_WOOCOMMERCE_ORDER_LIST
}