const AUTHENTICATED = 'AUTHENTICATED'
const NOT_AUTHENTICATED = 'NOT_AUTHENTICATED'
const ADD_competition = 'ADD_competition'
const GET_COMPANY_LIST = 'GET_COMPANY_LIST'
const GET_PRODUCT_LIST = 'GET_PRODUCT_LIST'
const GET_COMPETITION_LIST = 'GET_COMPETITION_LIST'

export {AUTHENTICATED, NOT_AUTHENTICATED, ADD_competition, GET_PRODUCT_LIST, GET_COMPANY_LIST, GET_COMPETITION_LIST}