version: '3.4'

services:
  hepsitools:
    container_name: hepsitools
    environment: 
       - ASPNETCORE_ENVIRONMENT=development
    ports:
       - "8001:80"
    volumes:
       - ${HOME}/.microsoft/usersecrets/:/root/.microsoft/usersecrets
       - ${HOME}/.aspnet/https:/root/.aspnet/https/